[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Medium" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
size = 12

[general]
import = [ "~/.config/alacritty/themes/themes/catppuccin_mocha.toml" ]

[env]
TERM = "xterm-256color"

[window]
opacity = 0.7
startup_mode = "Maximized"
dynamic_title = false
title = ""
decorations = "none"
padding = { x = 5, y = 0 }

[cursor.style]
shape = "Block"
blinking = "Never"
